name: azlogin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  azdeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: segraef/azlogin@v1
      with:
        clientId: "${{ secrets.clientId }}"
        clientSecret: "${{ secrets.clientSecret }}"
        tenantId: "${{ secrets.tenantId }}"
        subscriptionId: "${{ secrets.subscriptionId }}"
    - name: Azure ARM Deployment
      uses: segraef/azdeploy@v1
      with:
        resourceGroupName: ${{ secrets.resourceGroupName }}
        templateFile: ${{ secrets.templateFile }}
        parametersFile: ${{ secrets.parametersFile }}
        resourceGroupCommand: ${{ secrets.resourceGroupCommand }}